# Generated by Django 2.2 on 2021-04-29 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_app', '0002_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={},
        ),
    ]
