# Generated by Django 2.2 on 2021-04-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_app', '0003_auto_20210429_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='users',
            field=models.ManyToManyField(related_name='cities', to='group_app.User'),
        ),
    ]
