# Generated by Django 2.2 on 2021-05-03 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_app', '0005_zip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zip',
            name='city',
        ),
    ]
